import React, { FC } from "react";
import type { GetStaticProps } from 'next';
import Link from "next/link";
import Head from 'next/head';
import Image from 'next/image';
import { getSortedPostsData, PostType } from '../lib/posts';
import styles from '../styles/Home.module.css';

type HomeProps = {
  allPostsData:PostType[];
}

const Home: FC<HomeProps> = ({allPostsData}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
           Vítejte v zápiscích!
        </h1>

        <ul>
          {allPostsData.map(item => (
            <li key={item.id}>
              <Link href={`/${item.id}`}>{item.title}</Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const allPostsData = getSortedPostsData();
  return{
    props: {
      allPostsData,
    },
  };
}


export default Home
